[project]
name = "ritsu-pi"
version = "0.1.0"
description = "Full stack home server in Raspberry Pi"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible>=11.5.0",
    "ansible-core>=2.18.5",
    "ansible-lint>=25.4.0",
]
