---
- name: Restart Node Exporter
  service:
    name: node_exporter
    state: restarted

- name: Restart Prometheus
  community.docker.docker_compose_v2:
    state: restarted
    project_src: "{{ monitoring_config_dir }}"
    services:
      - prometheus

- name: Restart Grafana
  community.docker.docker_compose_v2:
    state: restarted
    project_src: "{{ monitoring_config_dir }}"
    services:
      - grafana

- name: Restart Mikrotik Exporter
  community.docker.docker_compose_v2:
    state: restarted
    project_src: "{{ monitoring_config_dir }}"
    services:
      - mikrotik

- name: Restart Blackbox Exporter
  community.docker.docker_compose_v2:
    state: restarted
    project_src: "{{ monitoring_config_dir }}"
    services:
      - blackbox
