---
immich_state: present
immich_port: 2283

immich_config_dir: "{{ config_root }}/immich"
immich_upload_dir: /var/lib/immich/uploads

immich_images:
  ml: ghcr.io/immich-app/immich-machine-learning:v2.5.3-openvino
  server: ghcr.io/immich-app/immich-server:v2.5.3
  postgres: ghcr.io/immich-app/postgres:18-vectorchord0.5.3-pgvector0.8.1
  redis: valkey/valkey:9

immich_hwaccel:
  ml: openvino
  transcoding: quicksync

immich_db:
  name: immich
  username: immich
  password: CHANGE-ME
  storage_type: HDD # HDD or SSD
